config/routes.rb
Rails.application.routes.draw do
    resources :students
    resources :teachers
    resources :exams
    resources :reports
    resources :payments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bayar.rb
class Bayar < ApplicationRecord
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def new #untuk menampilkan form data baru
    @exam = Exam.new
  end

  def create #untuk memperoses data baru yang dimasukkan di form new
    exam = Exam.new (resources_params)
    exam.save 
    redirect_to exams_path
    flash[:notice] = 'Exam has been created'
  end

  def edit #menampilkan data yang sudah disimpan
    @exam = Exam.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
 @exam = Exam.find(params[:id])
 @exam.update(resources_params)
 flash[:notice] = 'Exam has been update'
 redirect_to exams_path(@exam)
  end

  def destroy #untuk menghapus data
    @exam = Exam.find(params[:id])
    @exam.destroy
    flash[:notice] = 'Exam has been destroy'
    redirect_to exams_path(@exam)
  end
  
  def index #menampilkan seluruh data yang ada di database
    @exams = Exam.all
  end

  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @exam = Exam.find(id)
    # render plain: id
    # render plain: @book.title

  end
  private

  def resources_params
    params.required(:exam).permit(:title, :mapel, :duration, :nilai, :status, :level, :student_id)
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new #untuk menampilkan form data baru
    @payment = Payment.new
  end

  def create #untuk memperoses data baru yang dimasukkan di form new
    payment = Payment.new (resources_params)
    payment.save 
    redirect_to payments_path
    flash[:notice] = 'payment has been created'
  end

  def edit #menampilkan data yang sudah disimpan
    @payment = Payment.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
 @payment = Payment.find(params[:id])
 @payment.update(resources_params)
 flash[:notice] = 'Student has been update'
 redirect_to payments_path(@payment)
  end

  def destroy #untuk menghapus data
    @payment = Payment.find(params[:id])
    @payment.destroy
    flash[:notice] = 'Payment has been destroy'
    redirect_to payments_path(@payment)
  end
  
  def index #menampilkan seluruh data yang ada di database
    @payments = Payment.all
  end

  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @payment = Payment.find(id)
    # render plain: id
    # render plain: @book.title

  end
  private

  def resources_params
    params.required(:payment).permit(:id_transsction, :status, :upload)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def new #untuk menampilkan form data baru
    @report = Report.new
  end

  def create #untuk memperoses data baru yang dimasukkan di form new
    report = Report.new (resources_params)
    report.save 
    redirect_to reports_path
    flash[:notice] = 'Report has been created'
  end

  def edit #menampilkan data yang sudah disimpan
    @report = Report.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
 @report = Report.find(params[:id])
 @report.update(resources_params)
 flash[:notice] = 'Report has been update'
 redirect_to reports_path(@report)
  end

  def destroy #untuk menghapus data
    @report = Report.find(params[:id])
    @report.destroy
    flash[:notice] = 'Report has been destroy'
    redirect_to reports_path(@report)
  end
  
  def index #menampilkan seluruh data yang ada di database
    @reports = Report.all
  end

  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @report = Report.find(id)
    # render plain: id
    # render plain: @book.title

  end
  private

  def resources_params
    params.required(:report).permit(:title , :hasil , :mapel , :teacher_id , :student_id , :date)
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new #untuk menampilkan form data baru
    @student = Student.new
  end

  def create #untuk memperoses data baru yang dimasukkan di form new
    student = Student.new (resources_params)
    student.save 
    redirect_to students_path
    flash[:notice] = 'Student has been created'
  end

  def edit #menampilkan data yang sudah disimpan
    @student = Student.find(params[:id])
  end

  def update #melakukan proses ketika user mengedit data
 @student = Student.find(params[:id])
 @student.update(resources_params)
 flash[:notice] = 'Student has been update'
 redirect_to students_path(@student)
  end

  def destroy #untuk menghapus data
    @student = Student.find(params[:id])
    @student.destroy
    flash[:notice] = 'Book has been destroy'
    redirect_to students_path(@student)
  end
  
  def index #menampilkan seluruh data yang ada di database
    @students = Student.all
  end

  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @student = Student.find(id)
    # render plain: id
    # render plain: @book.title

  end
  private

  def resources_params
    params.required(:student).permit(:name, :username, :age, :rombel, :address, :city, :nik)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def new #untuk menampilkan form data baru
      @teacher = Teacher.new
    end
  
    def create #untuk memperoses data baru yang dimasukkan di form new
      teacher = Teacher.new (resources_params)
      teacher.save 
      redirect_to teachers_path
      flash[:notice] = 'teacher has been created'
    end
  
    def edit #menampilkan data yang sudah disimpan
      @teacher = Teacher.find(params[:id])
    end
  
    def update #melakukan proses ketika user mengedit data
   @teacher = Teacher.find(params[:id])
   @teacher.update(resources_params)
   flash[:notice] = 'Teacher has been update'
   redirect_to teachers_path(@teacher)
    end
  
    def destroy #untuk menghapus data
      @teacher = Teacher.find(params[:id])
      @teacher.destroy
      flash[:notice] = 'Book has been destroy'
      redirect_to teachers_path(@teacher)
    end
    
    def index #menampilkan seluruh data yang ada di database
      @teachers = Teacher.all
    end
  
    def show #menampilkan  sebuah data sectemplateara detail
      id = params[:id]
      @teacher = Teacher.find(id)
      # render plain: id
      # render plain: @book.title
  
    end
    private
  
    def resources_params
      params.required(:teacher).permit(:nik, :nama, :age, :kelas, :mapel)
    end
  
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/examps_helper.rb
module ExampsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <% if flash[:notice].present? %>
<%= flash [notice] %>
<% end %> </br>

    <%= form_for (@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>
    
    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>
    
    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>
    
    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>
    
    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>
    
    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>
    
    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>
    
    <%= f.submit  %>
    
    <% end %>
    <%= link_to 'Back', exams_path(), class: "btn btn-primary" %>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/exams/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<div class="container">
<table class="table">
    <tr>
        <td > Title</td>
        <td >  Mapel</td>
        <td >  Duration</td>
        <td >  Nilai</td>
        <td >  Status</td>
        <td >  level</td>
        <td >  Student_ID</td>
        <td colspan="5" > Action</td>
    </tr>
    <% @exams.each do |exam|%>
    <tr>
        <td><%= exam.title %> </td>
        <td><%= exam.mapel %> </td>
        <td><%= exam.duration %> </td>
        <td><%= exam.nilai %> </td>
        <td><%= exam.status %> </td>
        <td><%= exam.level %> </td>
        <td><%= exam.student_id %> </td>
<td>
    <div class="pull-right">
         <%= link_to 'Detail', exam_path(exam),  class: "btn btn-info"%> 
         <%= link_to 'Edit', edit_exam_path(exam), class: "btn btn-warning"%>
         <%= link_to 'Delete',  exam_path(exam), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%>
    </div>
    </tr>
</td>
<% end %>
</table>

<%= link_to 'New Exam', new_exam_path, class: "btn btn-primary"%> 
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/exams/new.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <%= form_for (@exam) do |f| %>
    <%= f.label :title %> </br>
    <%= f.text_field :title %> </br>
    
    <%= f.label :mapel %> </br>
    <%= f.text_field :mapel %> </br>
    
    <%= f.label :duration %> </br>
    <%= f.text_field :duration %> </br>
    
    <%= f.label :nilai %> </br>
    <%= f.text_field :nilai %> </br>
    
    <%= f.label :status %> </br>
    <%= f.text_field :status %> </br>
    
    <%= f.label :level %> </br>
    <%= f.text_field :level %> </br>
    
    <%= f.label :student_id %> </br>
    <%= f.text_field :student_id %> </br>
    
    <%= f.submit  %>
    
    <% end %>
    <%= link_to 'Back', exams_path(), class: "btn btn-primary" %>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kejarid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<div class="container">
<table class="table">
    <tr>
        <td > IDTaransaction</td>
        <td >  Status</td>
        <td >  Upload</td>
        <td colspan="5" > Action</td>
    </tr>
    <% @payments.each do |payment|%>
    <tr>
        <td><%= payment.id_transsction %> </td>
        <td><%= payment.status %> </td>
        <td><%= payment.upload %> </td>
        <td>
        <div class="pull-right">
        <%= link_to 'Detail', payment_path(payment), class: "btn btn-info"%>
        <%= link_to 'Edit', edit_payment_path(payment), class: "btn btn-warning"%> 
    <%= link_to 'Delete',  payment_path(payment), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%> 
    </div>
        </td>
    </tr>
<% end %>
</table>

<%= link_to 'New Student', new_payment_path, class: "btn btn-primary"%> 
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reports/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">


<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<div class="container">
    <table class="table">
        <tr>
        <td> Title</td>
        <td>  Hasil</td>
        <td>  Mapel</td>
        <td>  Teacher_ID</td>
        <td>  Student_ID</td>
        <td>  Date</td>
        <td colspan="5"> Action</td>
    </tr>
    <% @reports.each do |report|%>
    <tr>
        <td><%= report.title %> </td>
        <td><%= report.hasil %> </td>
        <td><%= report.mapel %> </td>
        <td><%= report.teacher_id %> </td>
        <td><%= report.student_id %> </td>
        <td><%= report.date %> </td>
<td>
    <div class="pull-right">
        <%= link_to 'Detail', report_path(report), class: "btn btn-info"%> 
        <%= link_to 'Edit', edit_report_path(report), class: "btn btn-warning"%> 
    <%= link_to 'Delete',  report_path(report), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%> 
    </div>
    </td>
    </tr>
<% end %>
</table>
<%= link_to 'New Report', new_report_path , class: "btn btn-primary"%> 
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/students/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>
<%= flash[:notice] %>
<% end %> </br>

<div class="container">
<table class="table">
    <tr>
        <td> Nama</td>
        <td>  Username</td>
        <td>  Age</td>
        <td>  Rombel</td>
        <td>  Address</td>
        <td>  City</td>
        <td>  Nik</td>
        <td colspan="5"> Action</td>
    </tr>
    <% @students.each do |student|%>
    <tr>
        <td><%= student.name %> </td>
        <td><%= student.username %> </td>
        <td><%= student.age %> </td>
        <td><%= student.rombel %> </td>
        <td><%= student.address %> </td>
        <td><%= student.city %> </td>
        <td><%= student.nik %> </td>
        <td>
            <div class="pull-right">
        <%= link_to 'Detail', student_path(student), class: "btn btn-info"%> 
        <%= link_to 'Edit', edit_student_path(student), class: "btn btn-warning"%> 
        <%= link_to 'Delete',  student_path(student), method: :delete, data: {confirm: 'Are you sure?'} ,class: "btn btn-danger"%>
    </div>
    </td>
    </tr>
<% end %>
</table>
<%= link_to 'New Student', new_student_path  ,class: "btn btn-primary"%> 

</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/teachers/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <% if flash[:notice].present? %>
    <%= flash[:notice] %>
    <% end %> </br>

<div class="container">
    <table class="table" >
        <tr>
        <td > Nik</td>
        <td >  Nama</td>
        <td>  Age</td>
        <td >  Kelas</td>
        <td>  Mapel</td>
        <td colspan="5" > Action</td>
    </tr>
    <% @teachers.each do |teacher|%>
    <tr>
        <td><%= teacher.nik %> </td>
        <td><%= teacher.nama %> </td>
        <td><%= teacher.age %> </td>
        <td><%= teacher.kelas %> </td>
        <td><%= teacher.mapel %> </td>
        <td>
            <div class="pull-right">
                <%= link_to 'Detail', teacher_path(teacher), class: "btn btn-info"%> 
                <%= link_to 'Edit', edit_teacher_path(teacher), class: "btn btn-warning"%> 
            <%= link_to 'Delete',  teacher_path(teacher), method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%> 
            </div>
            </td>
            </tr>
        <% end %>
        </table>
        <%= link_to 'New Teacher', new_teacher_path , class: "btn btn-primary"%> 
        </div>
        
        
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
            <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
          </body>
        </html>